services:
  timescaledb:
    image: pgvector/pgvector:pg15
    environment:
      - POSTGRES_DB=cctv
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5433:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg
    ports:
      - "8554:8554"
      - "8189:8189/tcp"
      - "8189:8189/udp"
      - "9997:9997"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml



volumes:
  timescaledb_data:
