from enum import Enum

class VisitorEventType(str, Enum):
    VISITOR_REGISTERED = "VISITOR_REGISTERED"
    EMPLOYEE_REGISTERED = "EMPLOYEE_REGISTERED"
    VISITOR_SYNCED = "VISITOR_SYNCED"
    VISITOR_RECOGNIZED = "VISITOR_RECOGNIZED"
    EMPLOYEE_RECOGNIZED = "EMPLOYEE_RECOGNIZED"
    VISITOR_ENTERED = "VISITOR_ENTERED"
    VISITOR_EXITED = "VISITOR_EXITED"
    VISIT_STARTED = "VISIT_STARTED"
    VISIT_COMPLETED = "VISIT_COMPLETED"
    LOW_CONFIDENCE_MATCH = "LOW_CONFIDENCE_MATCH"
    UNKNOWN_PERSON = "UNKNOWN_PERSON"
    PHOTO_UPDATED = "PHOTO_UPDATED"
