"""Add plugin tables

Revision ID: 0087d18d6c0d
Revises: 4ccf8fc33bbf
Create Date: 2026-07-29 11:45:27.845195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '0087d18d6c0d'
down_revision: Union[str, Sequence[str], None] = '4ccf8fc33bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anpr_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('plate_number', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('recognition_time_ms', sa.Float(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('detection_confidence', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anpr_events_camera_id'), 'anpr_events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_anpr_events_event_type'), 'anpr_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_anpr_events_id'), 'anpr_events', ['id'], unique=False)
    op.create_index(op.f('ix_anpr_events_plate_number'), 'anpr_events', ['plate_number'], unique=False)
    op.create_index(op.f('ix_anpr_events_timestamp'), 'anpr_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_anpr_events_track_id'), 'anpr_events', ['track_id'], unique=False)
    op.create_table('anpr_plate_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plate_number', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('vehicle_snapshot', sa.String(), nullable=True),
    sa.Column('plate_snapshot', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('lane', sa.String(), nullable=True),
    sa.Column('recognition_time_ms', sa.Float(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('detection_confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anpr_plate_history_camera_id'), 'anpr_plate_history', ['camera_id'], unique=False)
    op.create_index(op.f('ix_anpr_plate_history_id'), 'anpr_plate_history', ['id'], unique=False)
    op.create_index(op.f('ix_anpr_plate_history_plate_number'), 'anpr_plate_history', ['plate_number'], unique=False)
    op.create_index(op.f('ix_anpr_plate_history_timestamp'), 'anpr_plate_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_anpr_plate_history_track_id'), 'anpr_plate_history', ['track_id'], unique=False)
    op.create_table('anpr_statistics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date_bucket', sa.String(), nullable=True),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('total_detections', sa.Integer(), nullable=True),
    sa.Column('unique_plates', sa.Integer(), nullable=True),
    sa.Column('watchlist_matches', sa.Integer(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anpr_statistics_camera_id'), 'anpr_statistics', ['camera_id'], unique=False)
    op.create_index(op.f('ix_anpr_statistics_date_bucket'), 'anpr_statistics', ['date_bucket'], unique=False)
    op.create_index(op.f('ix_anpr_statistics_id'), 'anpr_statistics', ['id'], unique=False)
    op.create_table('anpr_vehicle_tracks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('best_plate', sa.String(), nullable=True),
    sa.Column('plate_confidence', sa.Float(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('vehicle_snapshot', sa.String(), nullable=True),
    sa.Column('plate_snapshot', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('lane', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anpr_vehicle_tracks_best_plate'), 'anpr_vehicle_tracks', ['best_plate'], unique=False)
    op.create_index(op.f('ix_anpr_vehicle_tracks_camera_id'), 'anpr_vehicle_tracks', ['camera_id'], unique=False)
    op.create_index(op.f('ix_anpr_vehicle_tracks_id'), 'anpr_vehicle_tracks', ['id'], unique=False)
    op.create_index(op.f('ix_anpr_vehicle_tracks_track_id'), 'anpr_vehicle_tracks', ['track_id'], unique=False)
    op.create_table('anpr_watchlists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plate_number', sa.String(), nullable=True),
    sa.Column('list_type', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('notification_rules', sa.JSON(), nullable=True),
    sa.Column('expiry', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anpr_watchlists_id'), 'anpr_watchlists', ['id'], unique=False)
    op.create_index(op.f('ix_anpr_watchlists_plate_number'), 'anpr_watchlists', ['plate_number'], unique=True)
    op.create_table('visitors',
    sa.Column('visitor_id', sa.String(), nullable=False),
    sa.Column('google_form_submission_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('face_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('total_visits', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('visitor_id')
    )
    op.create_index(op.f('ix_visitors_google_form_submission_id'), 'visitors', ['google_form_submission_id'], unique=False)
    op.create_index(op.f('ix_visitors_name'), 'visitors', ['name'], unique=False)
    op.create_index(op.f('ix_visitors_role'), 'visitors', ['role'], unique=False)
    op.create_index(op.f('ix_visitors_visitor_id'), 'visitors', ['visitor_id'], unique=False)
    op.create_table('visits',
    sa.Column('visit_id', sa.String(), nullable=False),
    sa.Column('visitor_id', sa.String(), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('snapshot_path', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.visitor_id'], ),
    sa.PrimaryKeyConstraint('visit_id')
    )
    op.create_index(op.f('ix_visits_visit_id'), 'visits', ['visit_id'], unique=False)
    op.create_index(op.f('ix_visits_visitor_id'), 'visits', ['visitor_id'], unique=False)
    op.create_table('visitor_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('visitor_id', sa.String(), nullable=True),
    sa.Column('visit_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('camera', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.visit_id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.visitor_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_visitor_events_event_id'), 'visitor_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_visitor_events_event_type'), 'visitor_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_visitor_events_visitor_id'), 'visitor_events', ['visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitor_events_visitor_id'), table_name='visitor_events')
    op.drop_index(op.f('ix_visitor_events_event_type'), table_name='visitor_events')
    op.drop_index(op.f('ix_visitor_events_event_id'), table_name='visitor_events')
    op.drop_table('visitor_events')
    op.drop_index(op.f('ix_visits_visitor_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_visit_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_visitors_visitor_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_role'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_name'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_google_form_submission_id'), table_name='visitors')
    op.drop_table('visitors')
    op.drop_index(op.f('ix_anpr_watchlists_plate_number'), table_name='anpr_watchlists')
    op.drop_index(op.f('ix_anpr_watchlists_id'), table_name='anpr_watchlists')
    op.drop_table('anpr_watchlists')
    op.drop_index(op.f('ix_anpr_vehicle_tracks_track_id'), table_name='anpr_vehicle_tracks')
    op.drop_index(op.f('ix_anpr_vehicle_tracks_id'), table_name='anpr_vehicle_tracks')
    op.drop_index(op.f('ix_anpr_vehicle_tracks_camera_id'), table_name='anpr_vehicle_tracks')
    op.drop_index(op.f('ix_anpr_vehicle_tracks_best_plate'), table_name='anpr_vehicle_tracks')
    op.drop_table('anpr_vehicle_tracks')
    op.drop_index(op.f('ix_anpr_statistics_id'), table_name='anpr_statistics')
    op.drop_index(op.f('ix_anpr_statistics_date_bucket'), table_name='anpr_statistics')
    op.drop_index(op.f('ix_anpr_statistics_camera_id'), table_name='anpr_statistics')
    op.drop_table('anpr_statistics')
    op.drop_index(op.f('ix_anpr_plate_history_track_id'), table_name='anpr_plate_history')
    op.drop_index(op.f('ix_anpr_plate_history_timestamp'), table_name='anpr_plate_history')
    op.drop_index(op.f('ix_anpr_plate_history_plate_number'), table_name='anpr_plate_history')
    op.drop_index(op.f('ix_anpr_plate_history_id'), table_name='anpr_plate_history')
    op.drop_index(op.f('ix_anpr_plate_history_camera_id'), table_name='anpr_plate_history')
    op.drop_table('anpr_plate_history')
    op.drop_index(op.f('ix_anpr_events_track_id'), table_name='anpr_events')
    op.drop_index(op.f('ix_anpr_events_timestamp'), table_name='anpr_events')
    op.drop_index(op.f('ix_anpr_events_plate_number'), table_name='anpr_events')
    op.drop_index(op.f('ix_anpr_events_id'), table_name='anpr_events')
    op.drop_index(op.f('ix_anpr_events_event_type'), table_name='anpr_events')
    op.drop_index(op.f('ix_anpr_events_camera_id'), table_name='anpr_events')
    op.drop_table('anpr_events')
    # ### end Alembic commands ###
