"""Add core camera and AI models

Revision ID: 4ccf8fc33bbf
Revises: 7f62bf9ef803
Create Date: 2026-07-23 22:52:08.947193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ccf8fc33bbf'
down_revision: Union[str, Sequence[str], None] = '7f62bf9ef803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('events', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_camera_timestamp', 'camera_events', ['camera_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_camera_events_camera_id'), 'camera_events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_camera_events_id'), 'camera_events', ['id'], unique=False)
    op.create_index(op.f('ix_camera_events_timestamp'), 'camera_events', ['timestamp'], unique=False)
    op.create_table('cameras',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rtsp_url', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rtsp_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cameras')
    op.drop_index(op.f('ix_camera_events_timestamp'), table_name='camera_events')
    op.drop_index(op.f('ix_camera_events_id'), table_name='camera_events')
    op.drop_index(op.f('ix_camera_events_camera_id'), table_name='camera_events')
    op.drop_index('idx_camera_timestamp', table_name='camera_events')
    op.drop_table('camera_events')
    # ### end Alembic commands ###
