"""Add indices to Camera model

Revision ID: 8799849ec13d
Revises: 0087d18d6c0d
Create Date: 2026-07-29 13:07:05.859233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8799849ec13d'
down_revision: Union[str, Sequence[str], None] = '0087d18d6c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_garbage_snapshots_id'), table_name='garbage_snapshots')
    op.drop_table('garbage_snapshots')
    op.drop_index(op.f('ix_garbage_analytics_camera_id'), table_name='garbage_analytics')
    op.drop_index(op.f('ix_garbage_analytics_date_bucket'), table_name='garbage_analytics')
    op.drop_index(op.f('ix_garbage_analytics_id'), table_name='garbage_analytics')
    op.drop_table('garbage_analytics')
    op.drop_index(op.f('ix_garbage_events_camera_id'), table_name='garbage_events')
    op.drop_index(op.f('ix_garbage_events_category'), table_name='garbage_events')
    op.drop_index(op.f('ix_garbage_events_id'), table_name='garbage_events')
    op.drop_index(op.f('ix_garbage_events_timestamp'), table_name='garbage_events')
    op.drop_table('garbage_events')
    op.create_index(op.f('ix_cameras_active'), 'cameras', ['active'], unique=False)
    op.create_index(op.f('ix_cameras_created_at'), 'cameras', ['created_at'], unique=False)
    op.create_index(op.f('ix_cameras_name'), 'cameras', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cameras_name'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_created_at'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_active'), table_name='cameras')
    op.create_table('garbage_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('zone_polygon', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('garbage_events_pkey'))
    )
    op.create_index(op.f('ix_garbage_events_timestamp'), 'garbage_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_garbage_events_id'), 'garbage_events', ['id'], unique=False)
    op.create_index(op.f('ix_garbage_events_category'), 'garbage_events', ['category'], unique=False)
    op.create_index(op.f('ix_garbage_events_camera_id'), 'garbage_events', ['camera_id'], unique=False)
    op.create_table('garbage_analytics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_bucket', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_events', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_breakdown', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('garbage_analytics_pkey'))
    )
    op.create_index(op.f('ix_garbage_analytics_id'), 'garbage_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_garbage_analytics_date_bucket'), 'garbage_analytics', ['date_bucket'], unique=False)
    op.create_index(op.f('ix_garbage_analytics_camera_id'), 'garbage_analytics', ['camera_id'], unique=False)
    op.create_table('garbage_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('full_frame_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('crop_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['garbage_events.id'], name=op.f('garbage_snapshots_event_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('garbage_snapshots_pkey'))
    )
    op.create_index(op.f('ix_garbage_snapshots_id'), 'garbage_snapshots', ['id'], unique=False)
    # ### end Alembic commands ###
