from enum import Enum

class ANPREventType(str, Enum):
    PLATE_DETECTED = "PLATE_DETECTED"
    NEW_PLATE = "NEW_PLATE"
    WHITELIST_MATCH = "WHITELIST_MATCH"
    BLACKLIST_MATCH = "BLACKLIST_MATCH"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    OCR_FAILED = "OCR_FAILED"
    DUPLICATE_PLATE = "DUPLICATE_PLATE"
    TRACK_STARTED = "TRACK_STARTED"
    TRACK_ENDED = "TRACK_ENDED"
